### ISSUE TITLE
Error in SW 5.5.1

### ISSUE THREAD

**Issue by Padrio** [FriendsOfShopware/FroshGrafana#2]
Hi there,

im trying to use this plugin but it does not seem to be compatible with Shopware 5.5.1.

```
[Fri Sep 28 21:11:33.037198 2018] [proxy_fcgi:error] [pid 17408:tid 140709612996352] [client 159.69.89.47:50412] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FroshGrafana\\Components\\Grafana\\QueryRequest::getTargets() must be of the type array, null returned in /var/wwwdomain.dehttpdocs/custom/plugins/FroshGrafana/Components/Grafana/QueryRequest.php:81
Stack trace:
#0 /var/wwwdomain.dehttpdocs/custom/plugins/FroshGrafana/Controllers/Widgets/Grafana.php(73): FroshGrafana\\Components\\Grafana\\QueryRequest->getTargets()
#1 /var/wwwdomain.dehttpdocs/engine/Library/Enlight/Controller/Action.php(193): Shopware_Controllers_Widgets_Grafana->queryAction()
#2 /var/wwwdomain.dehttpdocs/engine/Library/Enlight/Controller/Dispatcher/Default.php(549): Enlight_Controller_Action->dispatch('queryAction')
#3 /var/wwwdomain.dehttpdocs/engine/Library/Enlight/Controller/Front.php(222): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
#4 /var/wwwdomain.dehttpdocs/engine/S...'
```
Any ideas how to fix this? I tried booth, the `master` and `development` branch.

**Comment by Crease29** [comment]
This Plugin is currently in development. I could have a look at this particular error in the next days but it will not do what you expect, yet. Are you a developer and interested in contributing to this Plugin?

**Comment by Padrio** [comment]
Oh wow, didn't expected such a fast response. 
I'm a PHP developer which serves some Shopware shops for customers and my personal business. And now im looking forward into developing my own plugins and i stumbled upon this here. I have a TICK-Stack for metrics and want to adapt FroshGrafana to work with it.

**Comment by Crease29** [comment]
Could you please hava a look at the `rewrite` branch? This is my current state of work.
If you want you can contact me via mail (see link to my website on my profile) and we can discuss about future features what i'd like to approach and so on 🙂

**Comment by Padrio** [comment]
Works as expected, thank you! I'll fork this project soon.
